# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saque.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_saque(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_saque_cabecalho = QtWidgets.QFrame(self.centralwidget)
        self.frame_saque_cabecalho.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_saque_cabecalho.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_saque_cabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_saque_cabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_saque_cabecalho.setObjectName("frame_saque_cabecalho")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_saque_cabecalho)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_saque_voltar_menu = QtWidgets.QPushButton(self.frame_saque_cabecalho)
        self.pushButton_saque_voltar_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_saque_voltar_menu.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_saque_voltar_menu.setFont(font)
        self.pushButton_saque_voltar_menu.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"    \n"
"    color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_saque_voltar_menu.setObjectName("pushButton_saque_voltar_menu")
        self.verticalLayout_2.addWidget(self.pushButton_saque_voltar_menu)
        self.label_saque_string = QtWidgets.QLabel(self.frame_saque_cabecalho)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_saque_string.setFont(font)
        self.label_saque_string.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_saque_string.setObjectName("label_saque_string")
        self.verticalLayout_2.addWidget(self.label_saque_string)
        self.verticalLayout.addWidget(self.frame_saque_cabecalho)
        self.frame_saque_info = QtWidgets.QFrame(self.centralwidget)
        self.frame_saque_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_saque_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_saque_info.setObjectName("frame_saque_info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_saque_info)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_saque_rs = QtWidgets.QLabel(self.frame_saque_info)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_saque_rs.setFont(font)
        self.label_saque_rs.setObjectName("label_saque_rs")
        self.horizontalLayout.addWidget(self.label_saque_rs)
        self.lineEdit_saque_valor = QtWidgets.QLineEdit(self.frame_saque_info)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_saque_valor.setFont(font)
        self.lineEdit_saque_valor.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:rgb(45,45,45);\n"
"    border-bottom: 2px solid rgb(115,115,115);\n"
"\n"
"}")
        self.lineEdit_saque_valor.setObjectName("lineEdit_saque_valor")
        self.horizontalLayout.addWidget(self.lineEdit_saque_valor)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_saque_info)
        self.frame_saque_butao = QtWidgets.QFrame(self.centralwidget)
        self.frame_saque_butao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_saque_butao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_saque_butao.setObjectName("frame_saque_butao")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_saque_butao)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_saque_sacar = QtWidgets.QPushButton(self.frame_saque_butao)
        self.pushButton_saque_sacar.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_saque_sacar.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(115, 115, 115);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_saque_sacar.setObjectName("pushButton_saque_sacar")
        self.verticalLayout_4.addWidget(self.pushButton_saque_sacar)
        self.verticalLayout.addWidget(self.frame_saque_butao)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JUbank"))
        self.pushButton_saque_voltar_menu.setText(_translate("MainWindow", "<<"))
        self.label_saque_string.setText(_translate("MainWindow", "Qual é o valor da\n"
"saque ?"))
        self.label_saque_rs.setText(_translate("MainWindow", "R$"))
        self.pushButton_saque_sacar.setText(_translate("MainWindow", "Sacar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_saque()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
