# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_historico.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_historico(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setStyleSheet("background-color: rgb(138, 5, 190);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Login_logo = QtWidgets.QFrame(self.frame_3)
        self.frame_Login_logo.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_Login_logo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_Login_logo.setStyleSheet("\n"
"background-image: url(:/newPrefix/New_Piskel_(5).png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.frame_Login_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Login_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Login_logo.setObjectName("frame_Login_logo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Login_logo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_historico_cabecalho = QtWidgets.QLabel(self.frame_Login_logo)
        self.label_historico_cabecalho.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_historico_cabecalho.setFont(font)
        self.label_historico_cabecalho.setStyleSheet("QLabel{\n"
"color: rgb(115, 115, 115);\n"
"text-align: center;\n"
"}")
        self.label_historico_cabecalho.setObjectName("label_historico_cabecalho")
        self.horizontalLayout.addWidget(self.label_historico_cabecalho)
        self.verticalLayout_2.addWidget(self.frame_Login_logo)
        self.frame_login_cpf_cliente = QtWidgets.QFrame(self.frame_3)
        self.frame_login_cpf_cliente.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_login_cpf_cliente.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_login_cpf_cliente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_cpf_cliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_cpf_cliente.setObjectName("frame_login_cpf_cliente")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_login_cpf_cliente)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_historico = QtWidgets.QTextEdit(self.frame_login_cpf_cliente)
        self.textEdit_historico.setStyleSheet("QTextEdit{\n"
"    border-radius: 5px;\n"
"    padding 15px;\n"
"    background-color: rgb(115,115,115);\n"
"    color: rgb(255, 255, 255);\n"
"};\n"
"")
        self.textEdit_historico.setObjectName("textEdit_historico")
        self.verticalLayout.addWidget(self.textEdit_historico)
        self.verticalLayout_2.addWidget(self.frame_login_cpf_cliente)
        self.frame_login_loggar_entrar_cadastro = QtWidgets.QFrame(self.frame_3)
        self.frame_login_loggar_entrar_cadastro.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.frame_login_loggar_entrar_cadastro.setFont(font)
        self.frame_login_loggar_entrar_cadastro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_loggar_entrar_cadastro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_loggar_entrar_cadastro.setObjectName("frame_login_loggar_entrar_cadastro")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_login_loggar_entrar_cadastro)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_historic_voltar = QtWidgets.QPushButton(self.frame_login_loggar_entrar_cadastro)
        self.pushButton_historic_voltar.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_historic_voltar.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(115, 115, 115);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_historic_voltar.setObjectName("pushButton_historic_voltar")
        self.verticalLayout_4.addWidget(self.pushButton_historic_voltar)
        self.verticalLayout_2.addWidget(self.frame_login_loggar_entrar_cadastro)
        self.horizontalLayout_2.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_historico_cabecalho.setText(_translate("MainWindow", "Historico"))
        self.pushButton_historic_voltar.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_historico()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

