# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Deposito.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_deposito(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_deposito_voltar_menu = QtWidgets.QPushButton(self.frame)
        self.pushButton_deposito_voltar_menu.setGeometry(QtCore.QRect(10, 10, 15, 15))
        self.pushButton_deposito_voltar_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_deposito_voltar_menu.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_deposito_voltar_menu.setFont(font)
        self.pushButton_deposito_voltar_menu.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"    \n"
"    color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_deposito_voltar_menu.setObjectName("pushButton_deposito_voltar_menu")
        self.label_deposito_cabecalho = QtWidgets.QLabel(self.frame)
        self.label_deposito_cabecalho.setGeometry(QtCore.QRect(10, 30, 262, 46))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_deposito_cabecalho.setFont(font)
        self.label_deposito_cabecalho.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_deposito_cabecalho.setObjectName("label_deposito_cabecalho")
        self.verticalLayout.addWidget(self.frame)
        self.frame_deposito_info = QtWidgets.QFrame(self.centralwidget)
        self.frame_deposito_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_deposito_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_deposito_info.setObjectName("frame_deposito_info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_deposito_info)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_deposito_rs = QtWidgets.QLabel(self.frame_deposito_info)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_deposito_rs.setFont(font)
        self.label_deposito_rs.setObjectName("label_deposito_rs")
        self.horizontalLayout.addWidget(self.label_deposito_rs)
        self.lineEdit_deposito_valor = QtWidgets.QLineEdit(self.frame_deposito_info)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_deposito_valor.setFont(font)
        self.lineEdit_deposito_valor.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:rgb(45,45,45);\n"
"    border-bottom: 2px solid rgb(115,115,115);\n"
"\n"
"}")
        self.lineEdit_deposito_valor.setObjectName("lineEdit_deposito_valor")
        self.horizontalLayout.addWidget(self.lineEdit_deposito_valor)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_deposito_info)
        self.frame_deposito_butoes = QtWidgets.QFrame(self.centralwidget)
        self.frame_deposito_butoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_deposito_butoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_deposito_butoes.setObjectName("frame_deposito_butoes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_deposito_butoes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_deposito_depositar = QtWidgets.QPushButton(self.frame_deposito_butoes)
        self.pushButton_deposito_depositar.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_deposito_depositar.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(115, 115, 115);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_deposito_depositar.setObjectName("pushButton_deposito_depositar")
        self.verticalLayout_3.addWidget(self.pushButton_deposito_depositar)
        self.verticalLayout.addWidget(self.frame_deposito_butoes)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JUbank"))
        self.pushButton_deposito_voltar_menu.setText(_translate("MainWindow", "<<"))
        self.label_deposito_cabecalho.setText(_translate("MainWindow", "Qual é o valor do\n"
"deposito ?"))
        self.label_deposito_rs.setText(_translate("MainWindow", "R$"))
        self.pushButton_deposito_depositar.setText(_translate("MainWindow", "Depositar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_deposito()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
