# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setStyleSheet("background-color: rgb(138, 5, 190);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(272, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu_cabcalho = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu_cabcalho.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_menu_cabcalho.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_menu_cabcalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_cabcalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_cabcalho.setObjectName("frame_menu_cabcalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_menu_cabcalho)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_string_ola = QtWidgets.QLabel(self.frame_menu_cabcalho)
        self.label_string_ola.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_string_ola.setFont(font)
        self.label_string_ola.setStyleSheet("color: rgb(240, 233, 249);")
        self.label_string_ola.setObjectName("label_string_ola")
        self.horizontalLayout.addWidget(self.label_string_ola)
        self.lineEdit_menu_nome_sobrenome_cliente = QtWidgets.QLineEdit(self.frame_menu_cabcalho)
        self.lineEdit_menu_nome_sobrenome_cliente.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_menu_nome_sobrenome_cliente.setFont(font)
        self.lineEdit_menu_nome_sobrenome_cliente.setStyleSheet("\n"
"QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: rgb(240, 233, 249);\n"
"\n"
"}")
        self.lineEdit_menu_nome_sobrenome_cliente.setObjectName("lineEdit_menu_nome_sobrenome_cliente")
        self.horizontalLayout.addWidget(self.lineEdit_menu_nome_sobrenome_cliente)
        self.pushButton_voltar_login = QtWidgets.QPushButton(self.frame_menu_cabcalho)
        self.pushButton_voltar_login.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_voltar_login.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(193, 34, 255);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(175, 35, 255);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_voltar_login.setObjectName("pushButton_voltar_login")
        self.horizontalLayout.addWidget(self.pushButton_voltar_login)
        self.verticalLayout.addWidget(self.frame_menu_cabcalho)
        self.frame_informacoes = QtWidgets.QFrame(self.centralwidget)
        self.frame_informacoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_informacoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_informacoes.setObjectName("frame_informacoes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_informacoes)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_menu_informacoes_do_usuario = QtWidgets.QFrame(self.frame_informacoes)
        self.frame_menu_informacoes_do_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.frame_menu_informacoes_do_usuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_informacoes_do_usuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_informacoes_do_usuario.setObjectName("frame_menu_informacoes_do_usuario")
        self.label_menu_string_conta = QtWidgets.QLabel(self.frame_menu_informacoes_do_usuario)
        self.label_menu_string_conta.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_menu_string_conta.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_menu_string_conta.setObjectName("label_menu_string_conta")
        self.label_menu_string_saldo_disponivel = QtWidgets.QLabel(self.frame_menu_informacoes_do_usuario)
        self.label_menu_string_saldo_disponivel.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_menu_string_saldo_disponivel.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_menu_string_saldo_disponivel.setObjectName("label_menu_string_saldo_disponivel")
        self.pushButton_entrar_historico = QtWidgets.QPushButton(self.frame_menu_informacoes_do_usuario)
        self.pushButton_entrar_historico.setGeometry(QtCore.QRect(0, 230, 75, 23))
        self.pushButton_entrar_historico.setObjectName("pushButton_entrar_historico")
        self.layoutWidget = QtWidgets.QWidget(self.frame_menu_informacoes_do_usuario)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 129, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_menu_saldo_conta = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_menu_saldo_conta.setFont(font)
        self.lineEdit_menu_saldo_conta.setObjectName("lineEdit_menu_saldo_conta")
        self.horizontalLayout_3.addWidget(self.lineEdit_menu_saldo_conta)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_menu_informacoes_do_usuario)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 140, 102, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.frame_menu_informacoes_do_usuario)
        self.verticalLayout.addWidget(self.frame_informacoes)
        self.frame_menu_funcoes = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu_funcoes.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_menu_funcoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_funcoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_funcoes.setObjectName("frame_menu_funcoes")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_menu_funcoes)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_menu_entra_transferencia = QtWidgets.QPushButton(self.frame_menu_funcoes)
        self.pushButton_menu_entra_transferencia.setMinimumSize(QtCore.QSize(0, 55))
        self.pushButton_menu_entra_transferencia.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(193, 34, 255);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(175, 35, 255);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_menu_entra_transferencia.setObjectName("pushButton_menu_entra_transferencia")
        self.horizontalLayout_4.addWidget(self.pushButton_menu_entra_transferencia)
        self.pushButton_menu_entra_deposito = QtWidgets.QPushButton(self.frame_menu_funcoes)
        self.pushButton_menu_entra_deposito.setMinimumSize(QtCore.QSize(0, 55))
        self.pushButton_menu_entra_deposito.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(193, 34, 255);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(175, 35, 255);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_menu_entra_deposito.setObjectName("pushButton_menu_entra_deposito")
        self.horizontalLayout_4.addWidget(self.pushButton_menu_entra_deposito)
        self.pushButton_menu_entra_saque = QtWidgets.QPushButton(self.frame_menu_funcoes)
        self.pushButton_menu_entra_saque.setMinimumSize(QtCore.QSize(0, 55))
        self.pushButton_menu_entra_saque.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(193, 34, 255);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(175, 35, 255);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_menu_entra_saque.setObjectName("pushButton_menu_entra_saque")
        self.horizontalLayout_4.addWidget(self.pushButton_menu_entra_saque)
        self.verticalLayout.addWidget(self.frame_menu_funcoes)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JUbank"))
        self.label_string_ola.setText(_translate("MainWindow", "Olá,"))
        self.pushButton_voltar_login.setText(_translate("MainWindow", "X"))
        self.label_menu_string_conta.setText(_translate("MainWindow", "Conta"))
        self.label_menu_string_saldo_disponivel.setText(_translate("MainWindow", "Saldo siponivel"))
        self.pushButton_entrar_historico.setText(_translate("MainWindow", "Historico"))
        self.label_5.setText(_translate("MainWindow", "R$"))
        self.pushButton_menu_entra_transferencia.setText(_translate("MainWindow", "Transferencia"))
        self.pushButton_menu_entra_deposito.setText(_translate("MainWindow", "Deposito"))
        self.pushButton_menu_entra_saque.setText(_translate("MainWindow", "Saque"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_menu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
