# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfere.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_transfere(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_transf_cabecalho = QtWidgets.QFrame(self.centralwidget)
        self.frame_transf_cabecalho.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_transf_cabecalho.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_transf_cabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_transf_cabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_transf_cabecalho.setObjectName("frame_transf_cabecalho")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_transf_cabecalho)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_transf_voltar_menu = QtWidgets.QPushButton(self.frame_transf_cabecalho)
        self.pushButton_transf_voltar_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_transf_voltar_menu.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_transf_voltar_menu.setFont(font)
        self.pushButton_transf_voltar_menu.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"    \n"
"    color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_transf_voltar_menu.setObjectName("pushButton_transf_voltar_menu")
        self.verticalLayout_3.addWidget(self.pushButton_transf_voltar_menu)
        self.label_transf_cabecalho = QtWidgets.QLabel(self.frame_transf_cabecalho)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_transf_cabecalho.setFont(font)
        self.label_transf_cabecalho.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_transf_cabecalho.setObjectName("label_transf_cabecalho")
        self.verticalLayout_3.addWidget(self.label_transf_cabecalho)
        self.verticalLayout.addWidget(self.frame_transf_cabecalho)
        self.frame_trsf_info_valor = QtWidgets.QFrame(self.centralwidget)
        self.frame_trsf_info_valor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_trsf_info_valor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_trsf_info_valor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_trsf_info_valor.setObjectName("frame_trsf_info_valor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_trsf_info_valor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_transfe_rs = QtWidgets.QLabel(self.frame_trsf_info_valor)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_transfe_rs.setFont(font)
        self.label_transfe_rs.setObjectName("label_transfe_rs")
        self.horizontalLayout.addWidget(self.label_transfe_rs)
        self.lineEdit_transf_valor = QtWidgets.QLineEdit(self.frame_trsf_info_valor)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_transf_valor.setFont(font)
        self.lineEdit_transf_valor.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:rgb(45,45,45);\n"
"    border-bottom: 2px solid rgb(115,115,115);\n"
"\n"
"}")
        self.lineEdit_transf_valor.setText("")
        self.lineEdit_transf_valor.setObjectName("lineEdit_transf_valor")
        self.horizontalLayout.addWidget(self.lineEdit_transf_valor)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_trsf_info_valor)
        self.frame_transf_cabecalho_cpf = QtWidgets.QFrame(self.centralwidget)
        self.frame_transf_cabecalho_cpf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_transf_cabecalho_cpf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_transf_cabecalho_cpf.setObjectName("frame_transf_cabecalho_cpf")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_transf_cabecalho_cpf)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ = QtWidgets.QLabel(self.frame_transf_cabecalho_cpf)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_.setFont(font)
        self.label_.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_.setObjectName("label_")
        self.horizontalLayout_3.addWidget(self.label_)
        self.verticalLayout.addWidget(self.frame_transf_cabecalho_cpf)
        self.frame_trsnf_info = QtWidgets.QFrame(self.centralwidget)
        self.frame_trsnf_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_trsnf_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_trsnf_info.setObjectName("frame_trsnf_info")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_trsnf_info)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_trnsf_cpf = QtWidgets.QLineEdit(self.frame_trsnf_info)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_trnsf_cpf.setFont(font)
        self.lineEdit_trnsf_cpf.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:rgb(45,45,45);\n"
"    border-bottom: 2px solid rgb(115,115,115);\n"
"\n"
"}")
        self.lineEdit_trnsf_cpf.setObjectName("lineEdit_trnsf_cpf")
        self.horizontalLayout_4.addWidget(self.lineEdit_trnsf_cpf)
        self.verticalLayout.addWidget(self.frame_trsnf_info)
        self.frame_transf_butoes = QtWidgets.QFrame(self.centralwidget)
        self.frame_transf_butoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_transf_butoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_transf_butoes.setObjectName("frame_transf_butoes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_transf_butoes)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_trnsf_transferir = QtWidgets.QPushButton(self.frame_transf_butoes)
        self.pushButton_trnsf_transferir.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_trnsf_transferir.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(115, 115, 115);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.pushButton_trnsf_transferir.setObjectName("pushButton_trnsf_transferir")
        self.horizontalLayout_2.addWidget(self.pushButton_trnsf_transferir)
        self.verticalLayout.addWidget(self.frame_transf_butoes)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JUbank"))
        self.pushButton_transf_voltar_menu.setText(_translate("MainWindow", "<<"))
        self.label_transf_cabecalho.setText(_translate("MainWindow", "Qual é o valor da\n"
"transferência ?"))
        self.label_transfe_rs.setText(_translate("MainWindow", "R$"))
        self.label_.setText(_translate("MainWindow", "CPF da conta que deseja\n"
"transferir ?"))
        self.pushButton_trnsf_transferir.setText(_translate("MainWindow", "Transferir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_transfere()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
